In [1]:
#output ways

print ("Shreya")   # simple string output
print("shreya  "+"gupta",22)   #string concatenation and output of integer variable
print (22) #output of integer variable

Shreya
shreya  gupta 22
22


In [2]:
#variable building 

name = "shreya" #string variable
age = 22 #integer variable
price = 10.5 #float variable


In [3]:
# output of variables
print ("My name is ", name ) #output of string variable
age2 = age 
print (age2) #output of integer variable

My name is  shreya
22


In [4]:
# add two numbers

a=45
b=85
print(a+b)

130


In [5]:
# Arithmetic operations

print (a+b) # addition
print (a-b) # subtraction
print (a*b) # multiplication
print (a/b) #division
print (a%b) # modulus
print (a**b) #power

130
-40
3825
0.5294117647058824
45
333475299217836818538000898181106665229140523414065655135861579328062996798931325848731815598180211641932135790966640342958271503448486328125


In [6]:
#Relational operators

print (a==b) # equality
print (a!=b) #inequality
print (a>b) # greater than
print (a<b) # less than
print (a>=b) # greater than or equal to
print (a<=b) # less than or equal to

False
True
False
True
False
True


In [7]:
#Assignment operators

a += 10
print(a)  # or b = a; print(b)
a -= 10
print(a)  # or b = a; print(b)
a *= 10
print(a)  # or b = a; print(b)
a /= 10
print(a)  # or b = a; print(b)


55
45
450
45.0


In [8]:
#Logical operators

print (a and b) # and
print (a or b) # or
print (not a) # not
print (a and b or a and not b) # and and or and not

85
45.0
False
85


In [9]:
# Type conversion

print (str(a)) # string
print (int(a)) # integer
print (float(a)) # float

45.0
45
45.0


In [10]:
#type casting 

print (int(a)) # integer
print (float (a)) # float

45
45.0


In [11]:
#input function

name = input ("Enter your name:")
age = input ("Enter your age:")
print ("Hello, my name is", name, "and I am", age, "years old")

Enter your name: h
Enter your age: f


Hello, my name is h and I am f years old


In [12]:
#input 2 numbers and print their sum

a =input ("Enter no 1:")
b= input ("enter no 2 :")
sum= int (a)+int(b)
print ("Sum :",sum)

Enter no 1: 4
enter no 2 : 5


Sum : 9


In [13]:
#input sides of square and calculate area 

l= int (input("length:"))
area = l*l
print ("area of square :",area )

length: 4


area of square : 16


In [14]:
#input two float values and average 

a=int (input("enter no 1:"))
b=int (input("enter no 2:"))
average =(a+b)/2
print (float(average))

enter no 1: 4
enter no 2: 5


4.5


In [15]:
# input 2 numbers and return boolean  of greater or not 

a=int(input("Enter no 1:"))
b=int(input("Enter no 2:"))
print(a>=b)
print(a<b)


Enter no 1: 4
Enter no 2: 5


False
True


In [16]:
#concatenation 

fname = input ("first name")
lname =input ("last name ")
fullname =fname+lname 
print (fullname)

first name h
last name  h


hh


In [1]:
#length of str

str="array"
print(len(str))

5


In [2]:
#indexing 

str="array"
print (str[0])

a


In [6]:
#slicing 

str ="helloworld"
print (str[0:4])

hell


In [11]:
# string functions 

#1. str.ends with 

arr ="hello world"
print(str.endswith("d"))
print(str.capitalize())
print(str.replace("hello","hey"))
print(str.find("0"))
print(str.count("e"))


True
Helloworld
heyworld
-1
1


In [12]:
# take input first name and find length

fname=input("Enter your first name")
print(len(fname))

Enter your first name shreya


6


In [15]:
# find occurance of $

str = input ("Give the string $ 4 time")
print (str.count("$"))

Give the string $ 4 time $gh$hb$yh7bdjefkej


3


In [6]:
# Conditional statements 

marks =int( input("Enter your marks "))
if (marks >=90):
    print("Grade A")
elif(90>=marks and marks>=80):
        print("Grade B")
elif(80>=marks and marks>=70):
          print("Grade C")
elif(70>marks):
   print("Grade D")
else:
    print()





Enter your marks  45


Grade D


In [10]:
#nested Conditional

marks = int(input("Enter your marks: "))

if marks >= 70:
    if marks >= 80:
        if marks >= 90:
            print("Grade A")
        else:
            print("Grade B")
    else:
        print("Grade C")
else:
    print("Grade D")


Enter your marks:  45


Grade D


In [17]:
# input no. is odd or even

marks = int(input("Enter your marks: "))
if (marks %2 ==0):
    print("Even")
else:
    print("Odd")

Enter your marks:  10


Even


In [20]:
# find greatest number 

number1= int(input("First number"))
number2=int(input("Second number"))
number3=int(input("Third number"))

if (number1 >number2):
    print(number1)
elif(number2>number3):
    print(number2)
else:
    print(number3)

First number 8
Second number 10
Third number 5


10


In [27]:
# find multiple of 7 or not

number= int(input("Enter number"))
if (number %7==0):
    print("Multiple")
else:
    print("Not Multiple")


Enter number 21


Multiple


In [37]:
#list methods

list=[5,7,40]
print(list.append(10))
print(list)
print(list.sort())
print(list)
print(list.sort(reverse=True))
print(list)
print(list.insert(1,4))
print(list)
print(list.pop(4))
print(list)
print(list.remove(10))
print(list)
print(list[0:2])


None
[5, 7, 40, 10]
None
[5, 7, 10, 40]
None
[40, 10, 7, 5]
None
[40, 4, 10, 7, 5]
5
[40, 4, 10, 7]
None
[40, 4, 7]
[40, 4]


In [45]:
#tuple methods

list=(5,7,40)
print(list.index(7))
print(list)
print(list.count(7))
print(list)
print(list[0:2])

1
(5, 7, 40)
1
(5, 7, 40)
(5, 7)


In [47]:
# ask names of favorite movies and store in list

movie1=input("first movie")
movie2=input("Second movie")
movie3=input("third movie")
moviename=[movie1,movie2,movie3]
print (moviename)
print(type(moviename))

first movie zebra
Second movie gh
third movie uh


['zebra', 'gh', 'uh']
<class 'list'>


In [80]:
#check list is palindrome or not

list=[1,2,3,2,1]
list4=[1,"abc","abc",1]
b=(list.copy())
c=(list4.copy())
print(b)
print(c)
(b.reverse())
(c.reverse())
print(b)
print(c)
if (b==list and c==list4):
    
        print("List is palindrome")
else:
    print("List is not palindrome")


[1, 2, 3, 2, 1]
[1, 'abc', 'abc', 1]
[1, 2, 3, 2, 1]
[1, 'abc', 'abc', 1]
List is palindrome


In [64]:
#check list is palindrome or not

list=[1,"abc","abc",1]
b=(list.copy())
print(b)
(b.reverse())
print(b)
if (b==list):
    print("List is palindrome")
else:
    print("List is not palindrome")


[1, 'abc', 'abc', 1]
[1, 'abc', 'abc', 1]
List is palindrome


In [67]:
# count of number of students with "A"

Grades=("C","D","A","A","B","B","A")
print("Count of no.of students:",Grades.count("A"))

Count of no.of students: 3


In [82]:
# Sort the list A to D

Grades=["C","D","A","A","B","B","A"]
Grades.sort()
print("Sort of students Grades :",(Grades))

Sort of students Grades : ['A', 'A', 'A', 'B', 'B', 'C', 'D']


In [22]:
#Dict

dic={"fname":"Shreya","lname":"gupta","city":"Panna"}
print(type(dic))
dic7={}
print(dic7)
print(dic.keys())
print(dic.values())
print(dic.items())
dic7={"fname":"Hri"}
print(dic7)
dic.update(dic7)
print(dic)

<class 'dict'>
{}
dict_keys(['fname', 'lname', 'city'])
dict_values(['Shreya', 'gupta', 'Panna'])
dict_items([('fname', 'Shreya'), ('lname', 'gupta'), ('city', 'Panna')])
{'fname': 'Hri'}
{'fname': 'Hri', 'lname': 'gupta', 'city': 'Panna'}


In [43]:
#set

call={"fname","Shreya","lname","gupta","city","Panna"}
Grades={"C","D","A","A","B","B","A","city","Panna"}
print(type(call))
call1 = set()
print(call1)
call.remove("fname")
print(call)
call.add("fname")
print(call)
print(call.union(Grades))
print(call.intersection(Grades))
call.pop()
print(call)
call.clear()
print(call)

<class 'set'>
set()
{'Panna', 'Shreya', 'gupta', 'city', 'lname'}
{'Panna', 'Shreya', 'gupta', 'city', 'lname', 'fname'}
{'Panna', 'gupta', 'C', 'B', 'D', 'Shreya', 'city', 'lname', 'A', 'fname'}
{'Panna', 'city'}
{'Shreya', 'gupta', 'city', 'lname', 'fname'}
set()


In [44]:
#store word meaning in dic 

mydic={"table":["a piece of furniture ","list of facts & figures"],"cat":"a small animal"}
print(mydic)


{'table': ['a piece of furniture ', 'list of facts & figures'], 'cat': 'a small animal'}


In [1]:
# list of stu subj .Assume 1 classroom for 1 subj .calculated needed classroom for all students 

student_subjects = ["python", "java", "C++", "python", "javascript", "java", "python", "java", "C++", "C"]

# Use a set to get unique subjects
unique_subjects = set(student_subjects)
print("Unique subjects:", unique_subjects)

# Calculate number of classrooms
num_classrooms = len(unique_subjects)
print("Total classrooms needed:", num_classrooms)


Unique subjects: {'C', 'java', 'python', 'C++', 'javascript'}
Total classrooms needed: 5


In [10]:
# store marks in key values pairs 

mydic={}
print(mydic)

subject1=input("enter your subj1")
subject1_marks=input("enter your marks")
subject2=input("enter your subj2")
subject2_marks=input("enter your marks")
subject3=input("enter your subj3")
subject3_marks=input("enter your marks")

mydic[subject1]=subject1_marks
mydic[subject2]=subject2_marks
mydic[subject3]=subject3_marks
print(mydic)


{}
{'': ''}


In [11]:
# store 9 and 9.0

set={9,"9.0"}
print (set)


{9, '9.0'}


In [3]:
# print 1 to 100

i=1
while i<=100:
    print(i)
    i+=1

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [6]:
# print 100 to 1

i=100
while i>=1:
    print(i)
    i-=1

100
99
98
97
96
95
94
93
92
91
90
89
88
87
86
85
84
83
82
81
80
79
78
77
76
75
74
73
72
71
70
69
68
67
66
65
64
63
62
61
60
59
58
57
56
55
54
53
52
51
50
49
48
47
46
45
44
43
42
41
40
39
38
37
36
35
34
33
32
31
30
29
28
27
26
25
24
23
22
21
20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1


In [10]:
# print multiplication of n

n=int(input("Write your number"))
i=1
while (i<=10):
    print(n*i)
    i+=1


Write your number 4


4
8
12
16
20
24
28
32
36
40


In [18]:
# print list element one by one while loop

l =[1,4,9,16,25,36,49,64,81,100]
i=0
while (i<len(l)):
    print(l[i])
    i+=1

1
4
9
16
25
36
49
64
81
100


In [11]:
# search x element while loop

l =(1,4,9,16,25,36,49,64,81,100)
x= int(input("Enter your number"))
i=0
while i<len(l):
    if l[i]==x :
        print("Found",i)
    else:
        print("Not Found")
    i+=1

Enter your number 5


Not Found
Not Found
Not Found
Not Found
Not Found
Not Found
Not Found
Not Found
Not Found
Not Found


In [4]:
# print list element one by one for loop

list =[1,4,9,16,25,36,49,64,81,100]
for el in list:
    print(el)

1
4
9
16
25
36
49
64
81
100


In [33]:
#### search x element one by one for loop

l = (1, 4, 9, 16, 25, 36, 49, 64, 81, 100)
x = int(input("Write x element: "))
i = 0

for el in l:
    if el == x:
        print("Found at index", i)
        break
    i += 1
else:
    print("Not Found")
   

Write x element:  25


Found at index 4


In [1]:
# print 1 to 100 by for and range 

for i in range (1,101,1):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [3]:
# print 100 to 1 by for and range 

for i in range (100,0,-1):
    print(i)

100
99
98
97
96
95
94
93
92
91
90
89
88
87
86
85
84
83
82
81
80
79
78
77
76
75
74
73
72
71
70
69
68
67
66
65
64
63
62
61
60
59
58
57
56
55
54
53
52
51
50
49
48
47
46
45
44
43
42
41
40
39
38
37
36
35
34
33
32
31
30
29
28
27
26
25
24
23
22
21
20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1


In [1]:
# print multiplication of no. n by range and for 

n=int(input("write your no."))
for i in range (1,11,1):
    print(n*i)

write your no. 5


5
10
15
20
25
30
35
40
45
50


In [2]:
# find the sum of first natural numbers (using while )

i=1
sum=0
n = int(input("Enter a number: "))
while i<=n:
    sum +=i
    i+=1
print("sum is :",sum ) 


Enter a number:  5


sum is : 15


In [3]:
# find the sum of first natural numbers (using for)
sum = 0
n = int(input("Enter a number: "))
for i in range(1, n+1): 
    sum += i            
print("sum is :", sum)

Enter a number:  8


sum is : 36


In [4]:
# find the factorial of first natural numbers (for loop)
n = int(input("Enter a number: "))
fact=1
for i in range (1,n+1):
    fact*=i
print (fact)

Enter a number:  5


120


In [1]:
#find the factorial of first natural numbers (while loop)

i=1
fact=1
n = int(input("Enter a number: "))
while i<=n:
    fact*=i
    i+=1
print(fact)


Enter a number:  10


3628800


In [17]:
# calculate average by function 

def calc_average():
    sum = 0
    n = int(input("Enter a number: "))
    for i in range(1, n+1): 
        sum += i            
    average=sum/n
    print("sum is :", sum)
    print("average is :",average)
    return average

print("average is :",calc_average())






Enter a number:  4


sum is : 10
average is : 2.5
average is : 2.5


In [28]:
# calculate average by function  

a = int(input("Enter a number a: "))
b = int(input("Enter a number b: "))
c = int(input("Enter a number c: "))

def calc_average(a,b,c):
    sum=a+b+c
    print(sum)
    average =sum/3
    print(int(average))
    return (average)
calc_average(a,b,c)

Enter a number a:  4
Enter a number b:  5
Enter a number c:  5


14
4


4.666666666666667

In [30]:
# print the length of a list (list is the parameter)

def len_list(alphabet):
    print(len(alphabet))
    return (len(alphabet))

len_list(["a","b","c","d","c","h","d"])

7


7

In [39]:
# print the elements of a list in a single line(list is the parameter)

def prin_list(alphabet):
    i=0
    for i in range (i ,len(alphabet),1):
        print(alphabet[i],end="")
        
    
prin_list(["a","b","c","d","c","h","d"])

abcdchd

In [70]:
# print the factorial of n (n is the parameter)

def factorial (n):
    fact=1
    for i in range (1,n+1):
        fact*=i
        print(fact)
    return(fact)
        
factorial (5)

1
2
6
24
120


120

In [66]:
# conversion of usd to inr 

usd =int(input("Enter a number b: "))
def calc_inr(usd):
    conversion =83.5
    inr=usd*conversion
    print (inr)

calc_inr(usd)

Enter a number b:  5


417.5


In [96]:
# odd and even return function 

n =int(input("Enter a number n: "))
def odd_even (n):
    if n%2==0:
        print("Even")
    else:
        print("Odd")
odd_even(n)

Enter a number n:  10


Even


In [6]:
# write the function to sum of n natural number

def calc_sum(n):
    if (n<=0):
        return 0
    return n+calc_sum(n-1)
    
calc_sum(8)


36

In [26]:
# write a function to print whole list not in next line

def print_el (n):
    i=0
    for i in range (i,len(n),1):
        print(n[i],end="")
        
print_el(["a","b","c","e","i","h","d"])

abceihd

In [27]:
#Performing 3D Matrix

mat=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
mat


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [28]:
mat.ndim

3

In [29]:
#Performing 4D Matrix

mat=np.array([[[[1,2,3],[4,5,6]]],[[[7,8,9],[10,11,12]]],[[[13,14,15],[16,17,18]]],[[[19,20,21],[22,23,24]]]])
mat


array([[[[ 1,  2,  3],
         [ 4,  5,  6]]],


       [[[ 7,  8,  9],
         [10, 11, 12]]],


       [[[13, 14, 15],
         [16, 17, 18]]],


       [[[19, 20, 21],
         [22, 23, 24]]]])

In [30]:
mat.ndim

4

In [31]:
import numpy as np  
arr2=np.array([[1,2,3],[4,5,6]])
arr2


array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr2


array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
pip install kagglehub


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [34]:
import kagglehub


# Download latest version
path = kagglehub.dataset_download("kuchhbhi/cpga-iq-placement")

print("Path to dataset files:", path)



Path to dataset files: C:\Users\ASUS\.cache\kagglehub\datasets\kuchhbhi\cpga-iq-placement\versions\1


In [35]:
import os

print(os.listdir(path))


['student_clustering.csv']


In [36]:
import pandas as pd
import os

csv_file = os.path.join(path, "student_clustering.csv")  # use the exact filename from step 1
df = pd.read_csv(csv_file)

print(df.head())  # preview first 5 rows

   cgpa   iq
0  5.13   88
1  5.90  113
2  8.36   93
3  8.27   97
4  5.45  110


In [37]:
arr = df.values
print(arr)
print(type(arr)) 

[[  5.13  88.  ]
 [  5.9  113.  ]
 [  8.36  93.  ]
 [  8.27  97.  ]
 [  5.45 110.  ]
 [  5.88 109.  ]
 [  8.41  98.  ]
 [  8.8  115.  ]
 [  5.79 110.  ]
 [  8.09  94.  ]
 [  4.6   86.  ]
 [  6.1  110.  ]
 [  8.16  97.  ]
 [  5.    88.  ]
 [  5.71 108.  ]
 [  8.31  95.  ]
 [  5.5  111.  ]
 [  7.87  91.  ]
 [  6.05 111.  ]
 [  5.84 113.  ]
 [  7.47  98.  ]
 [  4.86  86.  ]
 [  7.78  92.  ]
 [  4.78  87.  ]
 [  4.96  88.  ]
 [  7.93  98.  ]
 [  4.86  87.  ]
 [  9.18 119.  ]
 [  8.04  94.  ]
 [  5.43 106.  ]
 [  8.86 117.  ]
 [  6.01 112.  ]
 [  8.83 118.  ]
 [  5.32 106.  ]
 [  7.77  96.  ]
 [  8.    96.  ]
 [  8.56 118.  ]
 [  5.91 108.  ]
 [  5.44  84.  ]
 [  5.57 113.  ]
 [  5.34  85.  ]
 [  8.43  96.  ]
 [  8.02  93.  ]
 [  5.31  86.  ]
 [  8.96 116.  ]
 [  8.78 116.  ]
 [  8.14  94.  ]
 [  6.4  108.  ]
 [  8.45 119.  ]
 [  5.67 109.  ]
 [  5.14  83.  ]
 [  4.95  86.  ]
 [  8.79 116.  ]
 [  8.12  96.  ]
 [  8.81 115.  ]
 [  6.05 108.  ]
 [  5.85 111.  ]
 [  8.88 115.  ]
 [  5.87 109. 

In [38]:
arr.ndim

2

In [39]:
arr2 = arr.reshape(2, 200)
print(arr2.shape)


(2, 200)


In [40]:
arr2


array([[  5.13,  88.  ,   5.9 , 113.  ,   8.36,  93.  ,   8.27,  97.  ,
          5.45, 110.  ,   5.88, 109.  ,   8.41,  98.  ,   8.8 , 115.  ,
          5.79, 110.  ,   8.09,  94.  ,   4.6 ,  86.  ,   6.1 , 110.  ,
          8.16,  97.  ,   5.  ,  88.  ,   5.71, 108.  ,   8.31,  95.  ,
          5.5 , 111.  ,   7.87,  91.  ,   6.05, 111.  ,   5.84, 113.  ,
          7.47,  98.  ,   4.86,  86.  ,   7.78,  92.  ,   4.78,  87.  ,
          4.96,  88.  ,   7.93,  98.  ,   4.86,  87.  ,   9.18, 119.  ,
          8.04,  94.  ,   5.43, 106.  ,   8.86, 117.  ,   6.01, 112.  ,
          8.83, 118.  ,   5.32, 106.  ,   7.77,  96.  ,   8.  ,  96.  ,
          8.56, 118.  ,   5.91, 108.  ,   5.44,  84.  ,   5.57, 113.  ,
          5.34,  85.  ,   8.43,  96.  ,   8.02,  93.  ,   5.31,  86.  ,
          8.96, 116.  ,   8.78, 116.  ,   8.14,  94.  ,   6.4 , 108.  ,
          8.45, 119.  ,   5.67, 109.  ,   5.14,  83.  ,   4.95,  86.  ,
          8.79, 116.  ,   8.12,  96.  ,   8.81, 115.  ,   6.05, 

In [2]:
import pandas as pd
import os

csv_file = os.path.join(path, "IPL Matches 2008-2020.csv")  # use the exact filename from step 1
df = pd.read_csv(csv_file)

print(df.head())  # preview first 5 rows

NameError: name 'path' is not defined